/*
 * SPDX-License-Identifier: BSD-2-Clause
 */

#ifndef __RISCV_XUANTIE_LINK_H__
#define __RISCV_XUANTIE_LINK_H__

/* HPCP reg */
#define XUANTIE_LINK_PMU_L3IMP				0x048
#define XUANTIE_LINK_PMU_L3MAUTHCR			0x200
#define XUANTIE_LINK_PMU_HPCPCOUNT0			0x500
#define XUANTIE_LINK_PMU_HPCPCOUNT1			0x508
#define XUANTIE_LINK_PMU_HPCPCOUNT2			0x510
#define XUANTIE_LINK_PMU_HPCPCOUNT3			0x518
#define XUANTIE_LINK_PMU_HPCPCOUNT4			0x520
#define XUANTIE_LINK_PMU_HPCPCOUNT5			0x528
#define XUANTIE_LINK_PMU_HPCPEVT0CR			0x540
#define XUANTIE_LINK_PMU_HPCPEVT1CR			0x548
#define XUANTIE_LINK_PMU_HPCPEVT2CR			0x550
#define XUANTIE_LINK_PMU_HPCPEVT3CR			0x558
#define XUANTIE_LINK_PMU_HPCPEVT4CR			0x560
#define XUANTIE_LINK_PMU_HPCPEVT5CR			0x568
#define XUANTIE_LINK_PMU_HPCPCNTOF			0x5c0
#define XUANTIE_LINK_PMU_HPCPMAUTHCR		0x5c8
#define XUANTIE_LINK_PMU_HPCPHAUTHCR		0x5d0 // XL300
#define XUANTIE_LINK_PMU_HPCPSAUTHCR		0x5d8
#define XUANTIE_LINK_PMU_HPCPINHIBIT		0x5e0
#define XUANTIE_LINK_PMU_HPCPINTPEND		0x5e8
#define XUANTIE_LINK_PMU_VENDOR_N_IMP_ID	0x600 // XL300

/* HPCP dev type */
#define XUANTIE_LINK_DEV_TYPE_XL100 100
#define XUANTIE_LINK_DEV_TYPE_XL200 200
#define XUANTIE_LINK_DEV_TYPE_XL300 300

int xuantie_link_pmu_device_init(void);

#endif // __RISCV_XUANTIE_LINK_H__
